# ---
# apiVersion: v1
# kind: Service
# metadata:
#   namespace: soulwallet
#   name: bundler-arb-sepolia
# spec:
#   type: ClusterIP
#   ports:
#     - port: 3000
#       targetPort: 3000
#   selector:
#     app: bundler-arb-sepolia
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   namespace: soulwallet
#   name: bundler-deployment-arb-sepolia
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: bundler-arb-sepolia
#   template:
#     metadata:
#       labels:
#         app: bundler-arb-sepolia
#     spec:
#       containers:
#         - name: bundler
#           image: 368469642629.dkr.ecr.us-west-2.amazonaws.com/soulwallet/bundler:latest
#           ports:
#           - containerPort: 3000
#           - containerPort: 9090
#           livenessProbe:
#             httpGet:
#               path: /
#               port: 3000
#           env:
#             - name: ENV
#               value: "DEV"
#             - name: ROUTE_PREFIX
#               value: "/bundler/arb-sepolia"
#             - name: IMAGE_TAG
#               value: "_IMAGE_TAG_VALUE_" # should be replaced with resolved image tag.
#             - name: CONFIG
#               value: "REMOTE"
#             - name: DEBUG
#               value: "*"
#             - name: BUNDLER_PARAM_MNEMONIC_PHRASE
#               value: "/bundler/dev/mnemonic"
#             - name: BUNDLER_PARAM_BENEFICIARY
#               value: "/bundler/dev/beneficiary"
#             - name: BUNDLER_PARAM_ENTRYPOINT
#               value: "/bundler/dev/entrypoint/06"
#             - name: BUNDLER_PARAM_NETWORK
#               value: "/bundler/arb/sepolia/dev/network"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   namespace: soulwallet
#   name: bundler-eth-sepolia
# spec:
#   type: ClusterIP
#   ports:
#     - port: 3000
#       targetPort: 3000
#   selector:
#     app: bundler-eth-sepolia
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   namespace: soulwallet
#   name: bundler-deployment-eth-sepolia
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: bundler-eth-sepolia
#   template:
#     metadata:
#       labels:
#         app: bundler-eth-sepolia
#     spec:
#       containers:
#         - name: bundler
#           image: 368469642629.dkr.ecr.us-west-2.amazonaws.com/soulwallet/bundler:latest
#           ports:
#           - containerPort: 3000
#           - containerPort: 9090
#           livenessProbe:
#             httpGet:
#               path: /
#               port: 3000
#           env:
#             - name: ENV
#               value: "DEV"
#             - name: ROUTE_PREFIX
#               value: "/bundler/eth-sepolia"
#             - name: IMAGE_TAG
#               value: "_IMAGE_TAG_VALUE_" # should be replaced with resolved image tag.
#             - name: CONFIG
#               value: "REMOTE"
#             - name: DEBUG
#               value: "*"
#             - name: BUNDLER_PARAM_MNEMONIC_PHRASE
#               value: "/bundler/dev/mnemonic"
#             - name: BUNDLER_PARAM_BENEFICIARY
#               value: "/bundler/dev/beneficiary"
#             - name: BUNDLER_PARAM_ENTRYPOINT
#               value: "/bundler/dev/entrypoint/06"
#             - name: BUNDLER_PARAM_NETWORK
#               value: "/bundler/eth/sepolia/dev/network" # Ethereum Sepolia RPC
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   namespace: soulwallet
#   name: bundler-op-sepolia
# spec:
#   type: ClusterIP
#   ports:
#     - port: 3000
#       targetPort: 3000
#   selector:
#     app: bundler-op-sepolia
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   namespace: soulwallet
#   name: bundler-deployment-op-sepolia
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: bundler-op-sepolia
#   template:
#     metadata:
#       labels:
#         app: bundler-op-sepolia
#     spec:
#       containers:
#         - name: bundler
#           image: 368469642629.dkr.ecr.us-west-2.amazonaws.com/soulwallet/bundler:latest
#           ports:
#           - containerPort: 3000
#           - containerPort: 9090
#           livenessProbe:
#             httpGet:
#               path: /
#               port: 3000
#           env:
#             - name: ENV
#               value: "DEV"
#             - name: ROUTE_PREFIX
#               value: "/bundler/op-sepolia"
#             - name: IMAGE_TAG
#               value: "_IMAGE_TAG_VALUE_" # should be replaced with resolved image tag.
#             - name: CONFIG
#               value: "REMOTE"
#             - name: DEBUG
#               value: "*"
#             - name: BUNDLER_PARAM_MNEMONIC_PHRASE
#               value: "/bundler/dev/mnemonic"
#             - name: BUNDLER_PARAM_BENEFICIARY
#               value: "/bundler/dev/beneficiary"
#             - name: BUNDLER_PARAM_ENTRYPOINT
#               value: "/bundler/dev/entrypoint/06"
#             - name: BUNDLER_PARAM_NETWORK
#               value: "/bundler/op/sepolia/dev/network" # Optimistic Sepolia RPC